using WorldXaml.Generator.Common;

namespace NFMWorld.LuaSourceGenerator;

internal sealed class LuaBindingInitGenerator(IReadOnlyList<BaseLuaTypeMetadata> types, string ns) : BaseLuaTypeGenerator
{
    public string GenerateCode()
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using NuLua;");
        sb.AppendLine("using NuLua.Luau;");
        sb.AppendLine("#pragma warning disable CS0162");
        sb.AppendLine("#pragma warning disable CS8600");
        sb.AppendLine("#pragma warning disable CS8601");
        sb.AppendLine("#pragma warning disable CS8602");
        sb.AppendLine("#pragma warning disable CS8604");
        sb.AppendLine("#pragma warning disable CS8631");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        using (sb.Block())
        {
            sb.AppendLine("partial class GeneratorGenerated");
            using (sb.Block())
            {
                EmitHelpers(sb);
            }

            sb.AppendLine("public static class LuaVisibleTypeRegistry");
            using (sb.Block())
            {
                EmitRegisterAll(sb);
            }
        }

        //
        sb.AppendLine("#pragma warning restore CS0162");
        sb.AppendLine("#pragma warning restore CS8600");
        sb.AppendLine("#pragma warning restore CS8601");
        sb.AppendLine("#pragma warning restore CS8602");
        sb.AppendLine("#pragma warning restore CS8604");
        sb.AppendLine("#pragma warning restore CS8631");
        return sb.ToString();
    }

    /// <summary>Emits the shared generated runtime helpers (once, on the GeneratorGenerated partial).</summary>
    private void EmitHelpers(IndentedStringBuilder sb)
    {
        sb.AppendLine("internal static void PushValue(global::NuLua.Luau.LuauState state, global::NuLua.LuaValue value)");
        using (sb.Block())
        {
            sb.AppendLine("state.Push(value);");
            sb.AppendLine("value.Dispose();");
        }
        sb.AppendLine();

        sb.AppendLine("internal static T ReadArg<T>(global::NuLua.Luau.LuauState state, global::NuLua.LuaValue value, int index)");
        using (sb.Block())
        {
            sb.AppendLine("if (value.TryRead<T>(out var result)) return result;");
            sb.AppendLine("state.RaiseError($\"bad argument #{index} (expected {typeof(T).Name})\");");
            sb.AppendLine("throw new global::System.InvalidOperationException(\"unreachable\");");
        }
        sb.AppendLine();

        sb.AppendLine("internal static T? ReadArgRef<T>(global::NuLua.Luau.LuauState state, global::NuLua.LuaValue value, int index) where T : class");
        using (sb.Block())
        {
            sb.AppendLine("if (value.Type is global::NuLua.LuaValueType.Nil) return null;");
            sb.AppendLine("if (value.TryRead<T>(out var result)) return result;");
            sb.AppendLine("state.RaiseError($\"bad argument #{index} (expected {typeof(T).Name})\");");
            sb.AppendLine("throw new global::System.InvalidOperationException(\"unreachable\");");
        }
        sb.AppendLine();

        sb.AppendLine("internal static T? ReadArgNullable<T>(global::NuLua.Luau.LuauState state, global::NuLua.LuaValue value, int index) where T : struct");
        using (sb.Block())
        {
            sb.AppendLine("if (value.Type is global::NuLua.LuaValueType.Nil) return null;");
            sb.AppendLine("if (value.TryRead<T>(out var result)) return result;");
            sb.AppendLine("state.RaiseError($\"bad argument #{index} (expected {typeof(T).Name})\");");
            sb.AppendLine("throw new global::System.InvalidOperationException(\"unreachable\");");
        }
        sb.AppendLine();

        sb.AppendLine("internal static bool TryConvertNullable<T>(global::NuLua.LuaValue value, out T? result) where T : struct");
        using (sb.Block())
        {
            sb.AppendLine("if (value.Type is global::NuLua.LuaValueType.Nil)");
            using (sb.Block())
            {
                sb.AppendLine("result = null;");
                sb.AppendLine("return true;");
            }
            sb.AppendLine("if (value.TryRead<T>(out var v))");
            using (sb.Block())
            {
                sb.AppendLine("result = v;");
                sb.AppendLine("return true;");
            }
            sb.AppendLine("result = null;");
            sb.AppendLine("return false;");
        }
        sb.AppendLine();
    }

    private void EmitRegisterAll(IndentedStringBuilder sb)
    {
        sb.AppendLine("public static void RegisterAll(global::NuLua.Luau.LuauState state)");
        using (sb.Block())
        {
            foreach (var type in types)
            {
                sb.AppendLine($"state[\"{type.LuaName}\"] = global::NuLua.LuaValue.FromTable(global::{ns}.GeneratorGenerated.{GetInitMethodName(type)}(state));");
            }
        }
    }
}