using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;
using WorldXaml.Generator.Common;

namespace NFMWorld.LuaSourceGenerator;

// TODO: lua/ts stubs, global static initializer on GeneratorGenerated
internal sealed class LuaBindingTypeGenerator(LuaTypeMetadata type, string ns) : BaseLuaTypeGenerator
{
    public string GenerateCode()
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using NuLua;");
        sb.AppendLine("using NuLua.Luau;");
        sb.AppendLine("#pragma warning disable CS0162");
        sb.AppendLine("#pragma warning disable CS8600");
        sb.AppendLine("#pragma warning disable CS8601");
        sb.AppendLine("#pragma warning disable CS8602");
        sb.AppendLine("#pragma warning disable CS8604");
        sb.AppendLine("#pragma warning disable CS8631");
        sb.AppendLine("#pragma warning disable CS0108");
        sb.AppendLine("#pragma warning disable CS8625");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        using (sb.Block())
        {
            sb.AppendLine("partial class GeneratorGenerated");
            using (sb.Block())
            {
                if (type.IsEnum)
                {
                    EmitEnumTypeTable(sb);
                }
                else
                {
                    EmitBindableMethods(sb, type.InstanceMethods);
                    EmitBindableMethods(sb, type.StaticMethods);
                    EmitBindableMethods(sb, type.Constructors);

                    if (type.HasStaticIndex)
                    {
                        EmitStaticIndex(sb);
                    }

                    if (type.HasStaticNewIndex)
                    {
                        EmitStaticNewIndex(sb);
                    }

                    EmitTypeTableInit(sb);
                }
            }
        }

        if (type.HasLuaVisibleAttr && !type.IsStatic && !type.IsEnum)
        {
            sb.AppendLine($"namespace {type.Namespace}");
            using (sb.Block())
            {
                EmitTypePartial(sb);
            }
        }

        //
        sb.AppendLine("#pragma warning restore CS0162");
        sb.AppendLine("#pragma warning restore CS8600");
        sb.AppendLine("#pragma warning restore CS8601");
        sb.AppendLine("#pragma warning restore CS8602");
        sb.AppendLine("#pragma warning restore CS8604");
        sb.AppendLine("#pragma warning restore CS8631");
        sb.AppendLine("#pragma warning restore CS0108");
        sb.AppendLine("#pragma warning restore CS8625");
        return sb.ToString();
    }

    /// <summary>Emits method delegate fields grouped by Lua name, skipping overloads/methods with unmarshallable types.</summary>
    private void EmitBindableMethods(IndentedStringBuilder sb, IEnumerable<LuaMethodMetadata> methods)
    {
        foreach (var group in methods.GroupBy(m => m.LuaName))
        {
            var bindable = group.Where(IsMethodBindable).ToArray();
            if (bindable.Length == 0)
            {
                sb.AppendLine($"#warning {type.TypeName}.{group.Key} skipped: no bindable overloads (unsupported parameter or return type)");
                continue;
            }
            EmitMethod(sb, bindable);
        }
    }

    // (Generated runtime helpers are emitted once in _init.cs.)

    private void EmitMethod(IndentedStringBuilder sb, IReadOnlyList<LuaMethodMetadata> overloads)
    {
        // Stable sort by OverloadPriority — ties keep collection (declaration) order,
        // which is the fallback order overload resolution tries candidates in.
        overloads = [.. overloads.OrderBy(m => m.OverloadPriority)];

        var baseMethod = overloads[0];

        var argOffset = baseMethod.IsStatic || baseMethod.IsInstanceConstructor ? 0 : 1;
        sb.AppendLine($"internal static readonly global::NuLua.LuaFunc<global::NuLua.Luau.LuauState> {GetFunctionName(type, baseMethod)} = (state, args) =>");
        using (sb.Block(end: "};"))
        {
            if (overloads.Count == 1)
            {
                EmitSingleOverloadBody(sb, baseMethod, argOffset);
            }
            else
            {
                EmitOverloadResolutionBody(sb, overloads, argOffset);
            }
        }
    }

    /// <summary>Emits the body for a method with a single overload — strict argument reads via ReadArg* helpers.</summary>
    private void EmitSingleOverloadBody(IndentedStringBuilder sb, LuaMethodMetadata baseMethod, int argOffset)
    {
        if (!baseMethod.IsStatic && !baseMethod.IsInstanceConstructor)
        {
            sb.AppendLine($"var instance = ReadArg<{type.FullTypeName}>(state, args[0], 0);");
        }

        for (var i = 0; i < baseMethod.Parameters.Length; i++)
        {
            var p = baseMethod.Parameters[i];
            var t = p.Type;
            if (t == null)
            {
                sb.AppendLine($"#error {p.TypeName} is not INamedTypeSymbol");
            }
            else
            {
                sb.AppendLine($"var arg{i} = {ReadArgExpression($"args[{i + argOffset}]", t, i + argOffset)};");
            }
        }

        EmitCallAndReturn(sb, baseMethod, "arg");
    }

    /// <summary>
    /// Emits runtime overload resolution: disambiguate overloads by the provided argument count,
    /// probe each candidate's parameters in priority order with TryRead, and execute the first match.
    /// </summary>
    private void EmitOverloadResolutionBody(IndentedStringBuilder sb, IReadOnlyList<LuaMethodMetadata> overloads, int argOffset)
    {
        var baseMethod = overloads[0];
        if (!baseMethod.IsStatic && !baseMethod.IsInstanceConstructor)
        {
            sb.AppendLine($"var instance = ReadArg<{type.FullTypeName}>(state, args[0], 0);");
        }

        foreach (var group in overloads.GroupBy(m => m.Parameters.Length).OrderBy(g => g.Key))
        {
            var parameterCount = group.Key;
            sb.AppendLine($"if (args.Length == {argOffset + parameterCount})");
            using (sb.Block())
            {
                for (var i = 0; i < parameterCount; i++)
                {
                    sb.AppendLine($"var raw{i} = args[{argOffset + i}];");
                }

                foreach (var candidate in group)
                {
                    EmitOverloadCandidate(sb, candidate, parameterCount);
                }
            }
        }

        sb.AppendLine($"state.RaiseError($\"No overload of '{baseMethod.LuaName}' matches the provided arguments.\");");
        sb.AppendLine("return 0;");
    }

    /// <summary>Emits one overload-resolution candidate: a TryRead probe chain that executes the method body on full match.</summary>
    private void EmitOverloadCandidate(IndentedStringBuilder sb, LuaMethodMetadata candidate, int parameterCount)
    {
        var probes = new List<string>(parameterCount);
        var preDeclared = new List<string>();
        for (var i = 0; i < candidate.Parameters.Length; i++)
        {
            var p = candidate.Parameters[i];
            var t = p.Type;
            if (t == null)
            {
                sb.AppendLine($"#error {p.TypeName} is not INamedTypeSymbol");
                return;
            }

            if (t.IsReferenceType)
            {
                // nil converts to null for reference-type parameters.
                // Assign into a pre-declared variable so it is definitely assigned even when the
                // probe short-circuits on nil.
                preDeclared.Add($"{t.FullTypeName} a{i} = null!;");
                probes.Add($"(raw{i}.Type is global::NuLua.LuaValueType.Nil || raw{i}.TryRead<{t.FullTypeName}>(out a{i}))");
            }
            else if (t.IsNullableValueType)
            {
                probes.Add($"TryConvertNullable<{t.FullTypeName[..^1]}>(raw{i}, out var a{i})");
            }
            else
            {
                probes.Add($"raw{i}.TryRead<{t.FullTypeName}>(out var a{i})");
            }
        }

        if (probes.Count == 0)
        {
            using (sb.Block())
            {
                EmitCallAndReturn(sb, candidate, "a");
            }
            return;
        }

        // Nested block scopes the out-vars declared in the if condition to this candidate,
        // so sibling candidates in the same count block can reuse the same variable names.
        using (sb.Block())
        {
            foreach (var declaration in preDeclared)
            {
                sb.AppendLine(declaration);
            }

            sb.AppendLine($"if ({string.Join(" && ", probes)})");
            using (sb.Block())
            {
                EmitCallAndReturn(sb, candidate, "a");
            }
        }
    }

    /// <summary>Emits the call site and return marshalling for a resolved overload. Arg variables are named '{argPrefix}{i}'.</summary>
    private void EmitCallAndReturn(IndentedStringBuilder sb, LuaMethodMetadata method, string argPrefix)
    {
        if (!method.IsVoid || method.IsInstanceConstructor)
        {
            sb.Append("var result = ");
        }

        var argExpressions = string.Join(", ", Enumerable.Range(0, method.Parameters.Length).Select(i => $"{argPrefix}{i}"));
        if (method is LuaConstructorMetadata)
        {
            sb.AppendLine($"new {method.DeclaringType?.FullTypeName}({argExpressions});");
        }
        else if (method.IsStatic)
        {
            sb.AppendLine($"{method.DeclaringType?.FullTypeName}.{method.Name}({argExpressions});");
        }
        else
        {
            sb.AppendLine($"instance.{method.Name}({argExpressions});");
        }

        if (method.IsVoid && !method.IsInstanceConstructor)
        {
            sb.AppendLine("return 0;");
        }
        else
        {
            var returnType = method.IsInstanceConstructor ? type : method.ReturnType;
            if (returnType != null)
            {
                sb.AppendLine($"PushValue(state, {MarshalToLua("state", "result", returnType)});");
            }
            else
            {
                sb.AppendLine($"#error {method.ReturnTypeName} is not INamedTypeSymbol");
            }
            sb.AppendLine("return 1;");
        }
    }

    /// <summary>Emits a static property/field index handler for the type table's metatable.</summary>
    private void EmitStaticIndex(IndentedStringBuilder sb)
    {
        sb.AppendLine($"internal static readonly global::NuLua.LuaFunc<global::NuLua.Luau.LuauState> {GetStaticMetamethodName(type, Metamethods.Index)} = (state, args) =>");
        using (sb.Block(end: "};"))
        {
            sb.AppendLine("var key = args[1];");
            sb.AppendLine("if (key.TryRead<string>(out var stringKey))");
            using (sb.Block())
            {
                foreach (var field in type.StaticFields.Where(f => IsMarshallable(f.FieldType)))
                {
                    sb.AppendLine($"if (stringKey == \"{field.LuaName}\") {{ PushValue(state, {MarshalToLua("state", $"{type.FullTypeName}.{field.Name}", field.FieldType)}); return 1; }}");
                }
                foreach (var prop in type.StaticProperties.Where(p => p.HasGetter && IsMarshallable(p.PropertyType)))
                {
                    sb.AppendLine($"if (stringKey == \"{prop.LuaName}\") {{ PushValue(state, {MarshalToLua("state", $"{type.FullTypeName}.{prop.Name}", prop.PropertyType)}); return 1; }}");
                }
            }
            sb.AppendLine("state.PushNil();");
            sb.AppendLine("return 1;");
        }
    }

    /// <summary>Emits a static property/field newindex handler for the type table's metatable.</summary>
    private void EmitStaticNewIndex(IndentedStringBuilder sb)
    {
        sb.AppendLine($"internal static readonly global::NuLua.LuaFunc<global::NuLua.Luau.LuauState> {GetStaticMetamethodName(type, Metamethods.NewIndex)} = (state, args) =>");
        using (sb.Block(end: "};"))
        {
            sb.AppendLine("var key = args[1];");
            sb.AppendLine("var value = args[2];");
            sb.AppendLine("if (key.TryRead<string>(out var stringKey))");
            using (sb.Block())
            {
                foreach (var field in type.StaticFields.Where(f => !f.IsReadOnly && IsMarshallable(f.FieldType)))
                {
                    sb.AppendLine($"if (stringKey == \"{field.LuaName}\") {{ {type.FullTypeName}.{field.Name} = {ReadArgExpression("value", field.FieldType, 2)}; return 0; }}");
                }
                foreach (var prop in type.StaticProperties.Where(p => p.HasSetter && IsMarshallable(p.PropertyType)))
                {
                    sb.AppendLine($"if (stringKey == \"{prop.LuaName}\") {{ {type.FullTypeName}.{prop.Name} = {ReadArgExpression("value", prop.PropertyType, 2)}; return 0; }}");
                }
                sb.AppendLine($"state.RaiseError($\"'{{stringKey}}' not found or read-only.\");");
            }
            sb.AppendLine("return 0;");
        }
    }

    /// <summary>Produces an argument read expression for <paramref name="t"/> from <paramref name="valueExpr"/>.</summary>
    private string ReadArgExpression(string valueExpr, BaseLuaTypeMetadata t, int index)
    {
        var prefix = $"global::{ns}.GeneratorGenerated.";
        if (t.IsReferenceType)
            return $"{prefix}ReadArgRef<{t.FullTypeName}>(state, {valueExpr}, {index})";
        if (t.IsNullableValueType)
            return $"{prefix}ReadArgNullable<{t.FullTypeName[..^1]}>(state, {valueExpr}, {index})";
        return $"{prefix}ReadArg<{t.FullTypeName}>(state, {valueExpr}, {index})";
    }

    /// <summary>Emits the per-state type-table factory for a non-enum type.</summary>
    private void EmitTypeTableInit(IndentedStringBuilder sb)
    {
        sb.AppendLine($"internal static global::NuLua.LuaTable {GetInitMethodName(type)}(global::NuLua.Luau.LuauState state)");
        using (sb.Block())
        {
            sb.AppendLine($"var typeTable = state.CreateTable(0, {type.StaticMethods.Count(IsMethodBindable) + type.Constructors.Count(IsMethodBindable) + type.InstanceMethods.Count(IsMethodBindable)});");

            foreach (var method in type.StaticMethods.Where(IsMethodBindable))
            {
                sb.AppendLine($"typeTable[\"{method.LuaName}\"] = global::NuLua.LuaValue.FromFunction(state.CreateFunction({GetFunctionName(type, method)}));");
            }
            foreach (var ctor in type.Constructors.Where(IsMethodBindable))
            {
                sb.AppendLine($"typeTable[\"{ctor.LuaName}\"] = global::NuLua.LuaValue.FromFunction(state.CreateFunction({GetFunctionName(type, ctor)}));");
            }
            // lua convention: static type table gets instance methods taking self as first parameter
            // it's very rare that you'd use these, but tooling expects it to be there
            foreach (var method in type.InstanceMethods.Where(IsMethodBindable))
            {
                sb.AppendLine($"typeTable[\"{method.LuaName}\"] = global::NuLua.LuaValue.FromFunction(state.CreateFunction({GetFunctionName(type, method)}));");
            }

            if (type.HasStaticIndex || type.HasStaticNewIndex)
            {
                sb.AppendLine("var typeTable_metatable = state.CreateTable(0, 2);");
                if (type.HasStaticIndex)
                {
                    sb.AppendLine($"typeTable_metatable[\"{Metamethods.Index}\"] = global::NuLua.LuaValue.FromFunction(state.CreateFunction({GetStaticMetamethodName(type, Metamethods.Index)}));");
                }
                if (type.HasStaticNewIndex)
                {
                    sb.AppendLine($"typeTable_metatable[\"{Metamethods.NewIndex}\"] = global::NuLua.LuaValue.FromFunction(state.CreateFunction({GetStaticMetamethodName(type, Metamethods.NewIndex)}));");
                }
                sb.AppendLine("state.PushValue(typeTable.Reference);");
                sb.AppendLine("state.SetMetatable(-1, typeTable_metatable);");
                sb.AppendLine("state.Pop(1);");
            }

            sb.AppendLine("return typeTable;");
        }
    }

    /// <summary>Emits the per-state type-table factory for an enum (members created via CreateEnumUserData).</summary>
    private void EmitEnumTypeTable(IndentedStringBuilder sb)
    {
        sb.AppendLine($"internal static global::NuLua.LuaTable {GetInitMethodName(type)}(global::NuLua.Luau.LuauState state)");
        using (sb.Block())
        {
            sb.AppendLine($"var typeTable = state.CreateTable(0, {type.EnumMembers.Length});");
            foreach (var member in type.EnumMembers)
            {
                sb.AppendLine($"typeTable[\"{member.LuaName}\"] = global::NuLua.LuaValue.FromUserData(state.CreateEnumUserData({type.FullTypeName}.{member.Name}));");
            }
            sb.AppendLine("return typeTable;");
        }
    }

    // ================================================================
    // ILuaUserData<T> partial type
    // ================================================================

    private void EmitTypePartial(IndentedStringBuilder sb)
    {
        sb.Append($"partial {(type.IsRecord ? "record " : "")}{(type.IsValueType ? "struct " : type.IsInterface ? "interface " : "class ")}{type.TypeName}");
        sb.Append($" : global::NuLua.ILuaUserData<{type.FullTypeName}>");
        sb.AppendLine();
        using (sb.Block())
        {
            EmitSupportedMetamethods(sb);
            EmitTryGetIndex(sb);
            EmitTrySetIndex(sb);
            EmitToLuaString(sb);
            if (!type.IsInterface)
            {
                EmitOperators(sb);
            }
        }
    }

    private void EmitSupportedMetamethods(IndentedStringBuilder sb)
    {
        sb.AppendLine("public static global::NuLua.LuaUserDataMetamethods SupportedMetamethods =>");
        using (sb.Indent())
        {
            var flags = new List<string>();
            if (type.HasIndex) flags.Add("global::NuLua.LuaUserDataMetamethods.Index");
            if (type.HasNewIndex) flags.Add("global::NuLua.LuaUserDataMetamethods.NewIndex");
            flags.Add("global::NuLua.LuaUserDataMetamethods.ToString");
            foreach (var op in type.Operators.Where(IsOperatorSupported))
            {
                if (OperatorMetamethodFlag(op.MetamethodName) is { } flag)
                    flags.Add($"global::NuLua.LuaUserDataMetamethods.{flag}");
            }

            for (var i = 0; i < flags.Count; i++)
            {
                sb.AppendLine($"{flags[i]}{(i == flags.Count - 1 ? ";" : "|")}");
            }
        }
    }

    private void EmitTryGetIndex(IndentedStringBuilder sb)
    {
        sb.AppendLine("public bool TryGetIndex(global::NuLua.Luau.LuauState state, global::NuLua.LuaValue key, out global::NuLua.LuaValue value)");
        using (sb.Block())
        {
            sb.AppendLine("if (key.TryRead<string>(out var stringKey))");
            using (sb.Block())
            {
                foreach (var field in type.InstanceFields.Where(f => IsMarshallable(f.FieldType)))
                {
                    sb.AppendLine($"if (stringKey == \"{field.LuaName}\") {{ value = {MarshalToLua("state", $"this.{field.Name}", field.FieldType)}; return true; }}");
                }
                foreach (var prop in type.InstanceProperties.Where(p => p.HasGetter && IsMarshallable(p.PropertyType)))
                {
                    sb.AppendLine($"if (stringKey == \"{prop.LuaName}\") {{ value = {MarshalToLua("state", $"this.{prop.Name}", prop.PropertyType)}; return true; }}");
                }
                foreach (var method in type.InstanceMethods.Where(IsMethodBindable))
                {
                    sb.AppendLine($"if (stringKey == \"{method.LuaName}\") {{ value = global::NuLua.LuaValue.FromFunction(state.CreateFunction(global::{ns}.GeneratorGenerated.{GetFunctionName(type, method)})); return true; }}");
                }
            }
            sb.AppendLine("value = default;");
            sb.AppendLine("return false;");
        }
    }

    private void EmitTrySetIndex(IndentedStringBuilder sb)
    {
        sb.AppendLine("public bool TrySetIndex(global::NuLua.Luau.LuauState state, global::NuLua.LuaValue key, global::NuLua.LuaValue value)");
        using (sb.Block())
        {
            sb.AppendLine("if (key.TryRead<string>(out var stringKey))");
            using (sb.Block())
            {
                foreach (var field in type.InstanceFields.Where(f => !f.IsReadOnly && IsMarshallable(f.FieldType)))
                {
                    sb.AppendLine($"if (stringKey == \"{field.LuaName}\") {{ this.{field.Name} = {ReadArgExpression("value", field.FieldType, 2)}; return true; }}");
                }
                foreach (var prop in type.InstanceProperties.Where(p => p.HasSetter && IsMarshallable(p.PropertyType)))
                {
                    sb.AppendLine($"if (stringKey == \"{prop.LuaName}\") {{ this.{prop.Name} = {ReadArgExpression("value", prop.PropertyType, 2)}; return true; }}");
                }
            }
            sb.AppendLine("return false;");
        }
    }

    private void EmitToLuaString(IndentedStringBuilder sb)
    {
        sb.AppendLine("public string? ToLuaString() => ToString();");
    }

    // ================================================================
    // Operators (ILuaUserData<T> static virtual members)
    // ================================================================

    private void EmitOperators(IndentedStringBuilder sb)
    {
        foreach (var op in type.Operators.Where(IsOperatorSupported))
        {
            EmitOperator(sb, op);
        }
    }

    /// <summary>Only same-type operands are supported — the userdata metamethod bridge reads both as T.</summary>
    private bool IsOperatorSupported(LuaOperatorMetadata op)
    {
        if (op.IsUnary)
            return op.Parameters.Length == 1 && op.Parameters[0].Type.FullTypeName == type.FullTypeName;
        return op.Parameters.Length == 2
            && op.Parameters[0].Type.FullTypeName == type.FullTypeName
            && op.Parameters[1].Type.FullTypeName == type.FullTypeName;
    }

    private void EmitOperator(IndentedStringBuilder sb, LuaOperatorMetadata op)
    {
        var methodName = OperatorMethodName(op.MetamethodName);
        var isBoolReturn = OperatorIsBoolean(op.MetamethodName);
        var selfType = type.FullTypeName;

        sb.Append($"public static {(isBoolReturn ? "bool" : "global::NuLua.LuaValue")} {methodName}(global::NuLua.Luau.LuauState state, {selfType} self");
        if (!op.IsUnary)
        {
            sb.Append($", {selfType} other");
        }
        sb.AppendLine(")");
        using (sb.Block())
        {
            var expr = op.IsUnary ? $"{op.Operator}self" : $"self {op.Operator} other";
            if (isBoolReturn)
            {
                sb.AppendLine($"return {expr};");
            }
            else
            {
                sb.AppendLine($"var result = {expr};");
                sb.AppendLine($"return global::NuLua.LuaValue.FromUserData(state.CreateUserData(result));");
            }
        }
    }

    private static string OperatorMethodName(string metamethod) => metamethod switch
    {
        Metamethods.Add => "Add",
        Metamethods.Sub => "Subtract",
        Metamethods.Div => "Divide",
        Metamethods.Mod => "Modulus",
        Metamethods.Unm => "UnaryMinus",
        Metamethods.Eq => "Equals",
        Metamethods.Lt => "LessThan",
        Metamethods.Le => "LessThanOrEqual",
        _ => throw new ArgumentOutOfRangeException(nameof(metamethod), metamethod, "Unsupported operator metamethod")
    };

    private static bool OperatorIsBoolean(string metamethod) =>
        metamethod is Metamethods.Eq or Metamethods.Lt or Metamethods.Le;

    private static string? OperatorMetamethodFlag(string metamethod) => metamethod switch
    {
        Metamethods.Add => "Add",
        Metamethods.Sub => "Sub",
        Metamethods.Div => "Div",
        Metamethods.Mod => "Mod",
        Metamethods.Unm => "Unm",
        Metamethods.Eq => "Eq",
        Metamethods.Lt => "Lt",
        Metamethods.Le => "Le",
        _ => null
    };

    private static bool IsMethodBindable(LuaMethodMetadata m) =>
        IsMarshallable(m.ReturnType) && m.Parameters.All(p => IsMarshallable(p.Type));
}

internal static class Metamethods
{
    public const string Metatable = "__metatable";
    public const string Index = "__index";
    public const string NewIndex = "__newindex";
    public const string Add = "__add";
    public const string Sub = "__sub";
    public const string Mul = "__mul";
    public const string Div = "__div";
    public const string Mod = "__mod";
    public const string Pow = "__pow";
    public const string Unm = "__unm";
    public const string Len = "__len";
    public const string Eq = "__eq";
    public const string Lt = "__lt";
    public const string Le = "__le";
    public const string Call = "__call";
    public const string Concat = "__concat";
    public const string Pairs = "__pairs";
    public const string IPairs = "__ipairs";
    public new const string ToString = "__tostring";
}

internal abstract class BaseLuaTypeGenerator
{
    protected static string MarshalToLua(string state, string variable, BaseLuaTypeMetadata variableType)
    {
        // Fixed-precision primitives → LuaValue.FromPrimitive (ids 0..3; metatables registered later).
        if (variableType.IsFixed64) return $"global::NuLua.LuaValue.FromPrimitive(0, {variable})";
        if (variableType.IsFixed64AngleSingle) return $"global::NuLua.LuaValue.FromPrimitive(1, {variable})";
        if (variableType.IsFixed64Euler) return $"global::NuLua.LuaValue.FromPrimitive(2, {variable})";
        if (variableType.IsFixed64Vector3) return $"global::NuLua.LuaValue.FromPrimitive(3, {variable})";

        // Nullable<T> marshals as the underlying value, or nil when null.
        if (variableType.IsNullableValueType)
        {
            var underlying = variableType.NullableUnderlyingType!;
            var inner = MarshalToLua(state, $"{variable}.Value", underlying);
            return $"({variable}.HasValue ? {inner} : global::NuLua.LuaValue.Nil)";
        }

        // Enums → CreateEnumUserData.
        if (variableType.IsEnum)
            return $"global::NuLua.LuaValue.FromUserData({state}.CreateEnumUserData({variable}))";

        // Userdata: [LuaVisible] types + hand-written ILuaUserData<T>.
        if (variableType.IsILuaUserData || (variableType.HasLuaVisibleAttr && !variableType.IsOpenGeneric && !variableType.IsConstructedGeneric))
            return $"global::NuLua.LuaValue.FromUserData({state}.CreateUserData({variable}))";

        // Lua-native pass-through values.
        if (variableType.IsLuaValue) return variable;
        if (variableType.IsLuaTable) return $"global::NuLua.LuaValue.FromTable({variable})";
        if (variableType.IsLuaFunction) return $"global::NuLua.LuaValue.FromFunction({variable})";
        if (variableType.IsLuaThread) return $"global::NuLua.LuaValue.FromThread({variable})";

        // Builtin scalars.
        switch (variableType.SpecialType)
        {
            case SpecialType.System_Boolean:
                return $"global::NuLua.LuaValue.FromBoolean({variable})";
            case SpecialType.System_String:
                return $"global::NuLua.LuaValue.FromString({variable})";
            case SpecialType.System_Char:
                return $"global::NuLua.LuaValue.FromString(({variable}).ToString())";
            default:
                // All remaining builtin numeric types marshall as numbers.
                if (variableType.IsBuiltIn)
                    return $"global::NuLua.LuaValue.FromNumber((double)({variable}))";
                return variable;
        }
    }

    /// <summary>True if a type can be marshalled to/from Lua in generated bindings.</summary>
    protected static bool IsMarshallable(BaseLuaTypeMetadata t)
    {
        if (t.IsNullableValueType)
            return IsMarshallable(t.NullableUnderlyingType!);
        return t.IsBuiltIn || t.IsEnum || t.IsILuaUserData || (t.HasLuaVisibleAttr && !t.IsOpenGeneric && !t.IsConstructedGeneric);
    }

    protected static string GetInitMethodName(BaseLuaTypeMetadata type) => $"Init_{ToIdentifier(type.LuaName)}";

    [return: NotNullIfNotNull(nameof(ns))]
    protected static string? ToIdentifier(string? ns) =>
        ns?.Replace(".", "_");
    protected static string GetFunctionName(BaseLuaTypeMetadata type, LuaMethodMetadata method) => $"__function_{(method.IsStatic ? "static_" : "")}{ToIdentifier(type.LuaName)}_{method.LuaName}";
    protected static string GetMetamethodName(BaseLuaTypeMetadata type, string metamethod) => $"__metamethod_{ToIdentifier(type.LuaName)}_{metamethod}";
    protected static string GetStaticMetamethodName(BaseLuaTypeMetadata type, string metamethod) => $"__metamethod__static_{ToIdentifier(type.LuaName)}_{metamethod}";
    protected static string GetMetatableName(BaseLuaTypeMetadata type) => $"__metatable_{ToIdentifier(type.LuaName)}";
    protected static string GetTypeTableName(BaseLuaTypeMetadata type) => $"__typeTable_{ToIdentifier(type.LuaName)}";
}
