using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;
using WorldXaml.Generator.Common;

namespace NFMWorld.LuaSourceGenerator;

internal sealed class LuaTableConverterGenerator(LuaTypeMetadata type, string ns) : BaseLuaTypeGenerator
{
    public string GenerateCode()
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0162");
        sb.AppendLine("#pragma warning disable CS8600");
        sb.AppendLine("#pragma warning disable CS8601");
        sb.AppendLine("#pragma warning disable CS8602");
        sb.AppendLine("#pragma warning disable CS8604");
        sb.AppendLine("#pragma warning disable CS8631");
        sb.AppendLine("#pragma warning disable CS0108");
        sb.AppendLine("#pragma warning disable CS8625");
        sb.AppendLine();
        sb.AppendLine($"namespace {type.Namespace}");
        using (sb.Block())
        {
            sb.Append($"{(type.IsStatic ? "static " : "")}partial {(type.IsRefStruct ? "ref " : "")}{(type.IsRecord ? "record " : "")}{(type.IsValueType ? "struct " : type.IsInterface ? "interface " : "class ")}{type.TypeName}");
            sb.Append($" : global::NFMWorld.Lua.ILuaValueConvertible<{type.FullTypeName}>");
            sb.AppendLine();
            using (sb.Block())
            {
                sb.AppendLine("public global::Lua.LuaValue ToLuaValue()");
                using (sb.Block())
                {
                    sb.AppendLine("var table = new global::Lua.LuaTable();");

                    foreach (var field in type.InstanceFields)
                    {
                        sb.Append($"table[\"{field.LuaName}\"] = ");
                        sb.Append(ToLuaValue(field.Name, field.FieldType));
                        sb.AppendLine(";");
                    }

                    foreach (var field in type.InstanceProperties)
                    {
                        sb.Append($"table[\"{field.LuaName}\"] = ");
                        sb.Append(ToLuaValue(field.Name, field.PropertyType));
                        sb.AppendLine(";");
                    }

                    sb.AppendLine("return table;");

                    static string ToLuaValue(string expression, BaseLuaTypeMetadata type)
                    {
                        if (type.IsBuiltIn) return expression;
                        if (type.IsArray) return $"global::NFMWorld.Lua.LuaTableHelper.ArrayToTable<{type.IEnumerableType.FullTypeName}>({expression})";
                        if (type.IsIList) return $"global::NFMWorld.Lua.LuaTableHelper.ListToTable<{type.IEnumerableType.FullTypeName}, {type.FullTypeName}>({expression})";
                        return $"{expression}.ToLuaValue()";
                    }
                }

                sb.AppendLine($"public static {type.FullTypeName} FromLuaValue(global::Lua.LuaValue tableValue)");
                using (sb.Block())
                {
                    sb.AppendLine("var table = tableValue.Read<global::Lua.LuaTable>();");
                    sb.AppendLine($"var value = new {type.FullTypeName}();");

                    foreach (var field in type.InstanceFields)
                    {
                        sb.Append($"value.{field.Name} = ");
                        sb.Append(ToValue($"table[\"{field.LuaName}\"]", field.FieldType));
                        sb.AppendLine(";");
                    }

                    foreach (var field in type.InstanceProperties)
                    {
                        sb.Append($"value.{field.Name} = ");
                        sb.Append(ToValue($"table[\"{field.LuaName}\"]", field.PropertyType));
                        sb.AppendLine(";");
                    }
                    
                    sb.AppendLine("return value;");

                    static string ToValue(string expression, BaseLuaTypeMetadata type)
                    {
                        if (type.IsBuiltIn) return $"{expression}.Read<{type.FullTypeName}>()";
                        if (type.IsArray) return $"global::NFMWorld.Lua.LuaTableHelper.ToArray<{type.IEnumerableType.FullTypeName}>({expression}.Read<global::Lua.LuaTable>())";
                        if (type.IsIList) return $"global::NFMWorld.Lua.LuaTableHelper.ToList<{type.IEnumerableType.FullTypeName}, {type.FullTypeName}>({expression}.Read<global::Lua.LuaTable>())";
                        return $"{type.FullTypeName}.FromLuaValue({expression})";
                    }
                }
            }
        }

        //
        sb.AppendLine("#pragma warning restore CS0162");
        sb.AppendLine("#pragma warning restore CS8600");
        sb.AppendLine("#pragma warning restore CS8601");
        sb.AppendLine("#pragma warning restore CS8602");
        sb.AppendLine("#pragma warning restore CS8604");
        sb.AppendLine("#pragma warning restore CS8631");
        sb.AppendLine("#pragma warning restore CS0108");
        sb.AppendLine("#pragma warning restore CS8625");
        return sb.ToString();
    }

}
