using Microsoft.Xna.Framework;
using NFMWorld.DriverInterface;

namespace NFMWorld.Reactor;

public static partial class Nodes
{
    public static StyleSheet Styles(
        Visibility? visibility = null,
        float? opacity = null,
        Direction? direction = null,
        FlexDirection? flexDirection = null,
        Justify? justifyContent = null,
        Align? alignItems = null,
        Align? alignSelf = null,
        Align? alignContent = null,
        Position? position = null,
        Wrap? flexWrap = null,
        Overflow? overflow = null,
        Display? display = null,
        float? flex = null,
        float? flexGrow = null,
        float? flexShrink = null,
        Node.MeasurementFlexBasis? flexBasis = null,
        Node.MeasurementMarginPosition? left = null,
        Node.MeasurementMarginPosition? top = null,
        Node.MeasurementMarginPosition? right = null,
        Node.MeasurementMarginPosition? bottom = null,
        Node.MeasurementMultiMargin? margin = null,
        Node.MeasurementMarginPosition? marginTop = null,
        Node.MeasurementMarginPosition? marginBottom = null,
        Node.MeasurementMarginPosition? marginLeft = null,
        Node.MeasurementMarginPosition? marginRight = null,
        Node.MeasurementMultiPadding? padding = null,
        Node.MeasurementPadding? paddingTop = null,
        Node.MeasurementPadding? paddingBottom = null,
        Node.MeasurementPadding? paddingLeft = null,
        Node.MeasurementPadding? paddingRight = null,
        Node.MeasurementMultiBorder? border = null,
        Node.Pixels? borderTop = null,
        Node.Pixels? borderBottom = null,
        Node.Pixels? borderLeft = null,
        Node.Pixels? borderRight = null,
        Node.MeasurementGap? gap = null,
        Node.MeasurementGap? gapColumn = null,
        Node.MeasurementGap? gapRow = null,
        BoxSizing? boxSizing = null,
        Node.MeasurementWidthHeight? width = null,
        Node.MeasurementWidthHeight? height = null,
        Node.MeasurementWidthHeight? minWidth = null,
        Node.MeasurementWidthHeight? minHeight = null,
        Node.MeasurementWidthHeight? maxWidth = null,
        Node.MeasurementWidthHeight? maxHeight = null,
        Node.Pixels? aspectRatio = null,
        Color? borderColor = null,
        Color? backgroundColor = null,
        float? borderRadius = null,
        float? borderTopLeftRadius = null,
        float? borderTopRightRadius = null,
        float? borderBottomLeftRadius = null,
        float? borderBottomRightRadius = null,
        Color? background = null,
        Color? foreground = null,
        Color? stroke = null,
        FontFamily? fontFamily = null,
        float? fontSize = null,
        FontStyle? fontStyle = null,
        BreakType? breakType = null,
        OverflowBehavior? overflowBehavior = null,
        TextHorizontalAlignment? horizontalAlignment = null,
        TextVerticalAlignment? verticalAlignment = null,
        Color? cursorColor = null,
        Color? selectionColor = null,
        Color? placeholderColor = null,
        
        // sub-sheets
        StyleSheet? hover = null,
        StyleSheet? active = null,
        StyleSheet? focus = null
    )
    {
        var @default = new StyleSheetStyles
        {
            Visibility = visibility,
            Opacity = opacity,
            Direction = direction,
            FlexDirection = flexDirection,
            JustifyContent = justifyContent,
            AlignItems = alignItems,
            AlignSelf = alignSelf,
            AlignContent = alignContent,
            Position = position,
            FlexWrap = flexWrap,
            Overflow = overflow,
            Display = display,
            Flex = flex,
            FlexGrow = flexGrow,
            FlexShrink = flexShrink,
            FlexBasis = flexBasis,
            Left = left,
            Top = top,
            Right = right,
            Bottom = bottom,
            Margin = margin,
            MarginTop = marginTop,
            MarginBottom = marginBottom,
            MarginLeft = marginLeft,
            MarginRight = marginRight,
            Padding = padding,
            PaddingTop = paddingTop,
            PaddingBottom = paddingBottom,
            PaddingLeft = paddingLeft,
            PaddingRight = paddingRight,
            Border = border,
            BorderTop = borderTop,
            BorderBottom = borderBottom,
            BorderLeft = borderLeft,
            BorderRight = borderRight,
            Gap = gap,
            GapColumn = gapColumn,
            GapRow = gapRow,
            BoxSizing = boxSizing,
            Width = width,
            Height = height,
            MinWidth = minWidth,
            MinHeight = minHeight,
            MaxWidth = maxWidth,
            MaxHeight = maxHeight,
            AspectRatio = aspectRatio,
            BorderColor = borderColor,
            BackgroundColor = backgroundColor,
            BorderRadius = borderRadius,
            BorderTopLeftRadius = borderTopLeftRadius,
            BorderTopRightRadius = borderTopRightRadius,
            BorderBottomLeftRadius = borderBottomLeftRadius,
            BorderBottomRightRadius = borderBottomRightRadius,
            Background = background,
            Foreground = foreground,
            Stroke = stroke,
            FontFamily = fontFamily,
            FontSize = fontSize,
            FontStyle = fontStyle,
            BreakType = breakType,
            OverflowBehavior = overflowBehavior,
            HorizontalAlignment = horizontalAlignment,
            VerticalAlignment = verticalAlignment,
            CursorColor = cursorColor,
            SelectionColor = selectionColor,
            PlaceholderColor = placeholderColor,
        };
        
        return new StyleSheet
        {
            Default = @default,
            Hover = hover?.Default ?? default,
            Active = active?.Default ?? default,
            Focus = focus?.Default ?? default
        };
    }
}