using nfm_world.ui.elements;
using nfm_world.ui.yoga;
using nfm_world.ui.yoga.xaml;

namespace nfm_world.ui.hud;

/// <summary>
/// Code-behind for LapTimerSplitsView.xaml.
/// The Build() and Populate() methods will be generated by the XamlX compiler.
/// </summary>
public partial class LapTimerSplitsView : Node
{
    /// <summary>
    /// Reference to the LapText TextBlock, set by XAML via Name lookup.
    /// </summary>
    public TextBlock? LapText { get; private set; }

    /// <summary>
    /// Reference to the LapIcon TextRun.
    /// </summary>
    public TextRun? LapIcon { get; private set; }

    /// <summary>
    /// Creates a new LapTimerSplitsView and initializes it from XAML.
    /// </summary>
    public LapTimerSplitsView()
    {
        // Call the generated Populate method to initialize from XAML
        // Once the XamlX build task runs, this will be wired up automatically.
        InitializeComponent();
    }

    /// <summary>
    /// Initializes the component from the compiled XAML.
    /// This method calls the generated Populate static method.
    /// </summary>
    private void InitializeComponent()
    {
        // The XamlX compiler will generate a static Populate method
        // that sets properties and creates the child hierarchy.
        // We call it through reflection for now, but after compilation
        // it will be directly available.
        XamlLoader.Populate(this);

        // After population, find named elements
        FindNamedElements();
    }

    /// <summary>
    /// Finds and caches references to named child elements.
    /// </summary>
    private void FindNamedElements()
    {
        LapText = FindChildByName<TextBlock>("LapText");
        LapIcon = FindChildByName<TextRun>("LapIcon");
    }

    /// <summary>
    /// Recursively finds a child node by name.
    /// </summary>
    private T? FindChildByName<T>(string name) where T : Node
    {
        return FindChildByNameRecursive<T>(this, name);
    }

    private static T? FindChildByNameRecursive<T>(Node parent, string name) where T : Node
    {
        foreach (var child in parent.Children)
        {
            if (child.Name == name && child is T typed)
                return typed;

            var found = FindChildByNameRecursive<T>(child, name);
            if (found != null)
                return found;
        }
        return null;
    }

    /// <summary>
    /// Updates the lap display text.
    /// </summary>
    /// <param name="currentLap">Current lap number (0-based).</param>
    /// <param name="totalLaps">Total number of laps.</param>
    public void SetLapText(int currentLap, int totalLaps)
    {
        if (LapText != null)
        {
            LapText.Text = $"{currentLap + 1}/{totalLaps}";
        }
    }
}
