using System;
using System.IO;
using Microsoft.CodeAnalysis;
using WorldXaml.Generator.Common;

namespace NFMWorld.ShaderSourceGen;

[Generator(LanguageNames.CSharp)]
public class FnaShaderIncrementalGenerator : IIncrementalGenerator
{
    private const string SourceItemGroupMetadata = "build_metadata.AdditionalFiles.SourceItemGroup";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var options = context.AnalyzerConfigOptionsProvider
            .WithTrackingName("AnalyzerConfigOptionsProvider");

        var effectFiles = context.AdditionalTextsProvider
            .Combine(options)
            .Where(static pair =>
            {
                var (text, options) = pair;
                
                var filePath = text.Path;
                if (!filePath.EndsWith(".fx", StringComparison.OrdinalIgnoreCase))
                {
                    return false;
                }

                if (!options.GetOptions(pair.Left).TryGetValue(SourceItemGroupMetadata, out var itemGroup)
                    || itemGroup != "FnaEffect")
                {
                    return false;
                }

                return true;
            })
            .Select(static (pair, _) => pair.Left)
            .WithTrackingName("EffectFiles");

        context.RegisterSourceOutput(effectFiles, static (context, text) =>
        {
            var path = text.Path;
            var sourceText = text.GetText();
            var effectName = Path.GetFileNameWithoutExtension(path);

            try
            {
                var parser = new HLSLParser(path, sourceText?.ToString() ?? string.Empty);
                var tree = new HLSLTree();
                
                var sb = new IndentedStringBuilder();
                if (!parser.Parse(tree))
                {
                    sb.AppendLine("// Failed to parse HLSL file:");
                }

                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("#nullable disable");
                sb.AppendLine();
                sb.AppendLine("namespace NFMWorld.Shaders.Generated;");
                sb.AppendLine();
                sb.AppendLine($"partial sealed class {effectName}");
                sb.AppendLine("{");
                using (sb.Indent())
                {
                    sb.AppendLine("public Effect UnderlyingEffect { get; }");
                    sb.AppendLine("private bool _shouldDispose;");
                    sb.AppendLine();
                    sb.AppendLine($"public {effectName}(GraphicsDevice graphicsDevice, byte[] effectCode)");
                    sb.AppendLine("{");
                    using (sb.Indent())
                    {
                        sb.AppendLine("UnderlyingEffect = new Effect(graphicsDevice, effectCode)");
                        sb.AppendLine("{");
                        using (sb.Indent())
                        {
                            sb.AppendLine($"Name = \"{effectName}\"");
                        }

                        sb.AppendLine("};");
                        sb.AppendLine("_shouldDispose = true;");
                        sb.AppendLine("InitParameters();");
                    }

                    sb.AppendLine("}");
                    sb.AppendLine();
                    sb.AppendLine($"public {effectName}(Effect underlyingEffect)");
                    sb.AppendLine("{");
                    using (sb.Indent())
                    {
                        sb.AppendLine("UnderlyingEffect = underlyingEffect;");
                        sb.AppendLine("_shouldDispose = false;");
                        sb.AppendLine("InitParameters();");
                    }

                    sb.AppendLine("}");
                    sb.AppendLine();
                    sb.AppendLine($"~{effectName}()");
                    sb.AppendLine("{");
                    using (sb.Indent())
                    {
                        sb.AppendLine("if (_shouldDispose)");
                        sb.AppendLine("{");
                        using (sb.Indent())
                        {
                            sb.AppendLine("UnderlyingEffect.Dispose();");
                            sb.AppendLine("_shouldDispose = false;");
                        }

                        sb.AppendLine("}");
                    }

                    sb.AppendLine();
                    sb.AppendLine("private void InitParameters()");
                    sb.AppendLine("{");
                    using (sb.Indent())
                    {
                        foreach (var statement in tree.Root.Statements())
                        {
                            if (statement is HLSLDeclaration declaration)
                            {
                                sb.AppendLine(
                                    $"var __{declaration.Name} = UnderlyingEffect.Parameters[\"{declaration.Name}\"];");
                                sb.AppendLine(
                                    $"if (__{declaration.Name} != null) this.{declaration.Name} = new {declaration.Type.BaseType}EffectParameter(__{declaration.Name});");
                            }
                        }
                    }

                    sb.AppendLine("}");

                    foreach (var statement in tree.Root.Statements())
                    {
                        if (statement is HLSLDeclaration declaration)
                        {
                            sb.AppendLine(
                                $"public {declaration.Type.BaseType}EffectParameter? {declaration.Name} {{ get; }}");
                        }
                    }
                }

                sb.AppendLine("}");
                context.AddSource($"{effectName}.g.cs", sb.ToString());
            }
            catch (Exception ex)
            {
                context.AddSource($"{effectName}.g.cs", ex.ToString());
            }
        });
    }
}