using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using WorldXaml.Generator.Common;

namespace WorldXaml.Generator;

[Generator(LanguageNames.CSharp)]
public class PropertyGenerator : IIncrementalGenerator
{
    private const string PropertyAttrFqn = "WorldXaml.UI.Base.PropertyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var props = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                PropertyAttrFqn,
                static (node, _) => node is PropertyDeclarationSyntax,
                static (ctx, _) =>
                {
                    var propSymbol = (IPropertySymbol)ctx.TargetSymbol;
                    var typeSymbol = propSymbol.ContainingType;

                    // Check if the class already defines a static *Property field
                    var backingFieldName = propSymbol.Name + "Property";
                    var hasBackingField = typeSymbol.GetMembers(backingFieldName).Any(m => m.IsStatic);

                    var attr = ctx.Attributes[0];

                    var defaultValue = GetNamedArg(attr, "DefaultValue");
                    var defaultValueMember = GetNamedArg(attr, "DefaultValueMember");
                    var onChangedMethod = GetNamedArg(attr, "OnChangedMethod");

                    var hierarchy = new List<(string Name, bool IsRecord, bool IsValueType, ImmutableArray<string>)>();
                    var t = typeSymbol;
                    while (t is not null)
                    {
                        hierarchy.Add((t.Name, t.IsRecord, t.IsValueType, t.TypeArguments.Select(ta => ta.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).ToImmutableArray()));
                        t = t.ContainingType;
                    }
                    hierarchy.Reverse();

                    return new PropInfo(
                        DeclaringNamespace: typeSymbol.ContainingNamespace.ToDisplayString(),
                        Hierarchy: hierarchy,
                        PropertyName: propSymbol.Name,
                        PropertyType: propSymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        IsNullableReference: propSymbol.NullableAnnotation == NullableAnnotation.Annotated
                            && !propSymbol.Type.IsValueType,
                        DefaultValue: defaultValue,
                        DefaultValueMember: defaultValueMember?.Replace("\"", ""),
                        OnChangedMethod: onChangedMethod?.Replace("\"", ""),
                        HasBackingField: hasBackingField);
                })
                .WithTrackingName("PropertyDeclarations");

        context.RegisterSourceOutput(
            props.Collect(),
            (spc, props) =>
            {
                if (props.IsEmpty) return;

                var grouped = props.GroupBy(static prop => (prop.DeclaringNamespace, prop.Hierarchy), HierarchyComparer.Instance);

                foreach (var group in grouped)
                {
                    var first = group.First();
                    var containingTypes = string.Join(".", first.Hierarchy.Select(h => h.Type));
                    var fullType = $"global::{first.DeclaringNamespace}.{containingTypes}";

                    var sb = new IndentedStringBuilder();
                    sb.AppendLine("// <auto-generated />");
                    sb.AppendLine("#nullable enable");
                    sb.AppendLine($"namespace {first.DeclaringNamespace};");
                    sb.AppendLine();

                    foreach (var type in group.Key.Hierarchy)
                    {
                        sb.AppendLine($"partial {(type.IsRecord ? "record" : type.IsStruct ? "struct" : "class")} {type.Type}");
                        sb.AppendLine("{");
                        sb.IncrementIndent();
                    }

                    foreach (var prop in group)
                    {
                        var propType = prop.IsNullableReference ? $"{prop.PropertyType}?" : prop.PropertyType;
                        var propName = prop.PropertyName;

                        // Determine default value expression
                        var defaultExpr = prop.DefaultValueMember ?? prop.DefaultValue ?? $"default({prop.PropertyType}{(prop.IsNullableReference ? "?" : "")})";

                        // Build onChanged delegate
                        var onChanged = prop.OnChangedMethod is { } om
                            ? $"(obj, value) => obj.{om}(value)"
                            : "null";

                        if (!prop.HasBackingField)
                        {
                            sb.AppendLine($"/// <summary>");
                            sb.AppendLine($"/// Property field for <see cref=\"{propName}\"/>.");
                            sb.AppendLine($"/// </summary>");

                            sb.AppendLine($"public static global::WorldXaml.UI.Property<{propType}> {propName}Property {{ get; }} =");
                            using (sb.Indent())
                            {
                                sb.AppendLine($"global::WorldXaml.UI.Property.Register<{fullType}, {propType}>(");
                                using (sb.Indent())
                                {
                                    sb.AppendLine($"nameof({propName}),");
                                    sb.AppendLine($"defaultValue: {defaultExpr},");
                                    sb.AppendLine($"onChanged: {onChanged});");
                                }
                            }
                            
                            sb.AppendLine();
                        }

                        if (prop.OnChangedMethod is not null)
                        {
                            sb.AppendLine($"private partial void {prop.OnChangedMethod}({propType} value);");
                            sb.AppendLine();
                        }

                        if (prop.DefaultValueMember is not null)
                        {
                            sb.AppendLine($"private static partial {propType} {prop.DefaultValueMember} {{ get; }}");
                            sb.AppendLine();
                        }

                        sb.AppendLine($"public partial {propType} {propName}");
                        sb.AppendLine($"{{");
                        using (sb.Indent())
                        {
                            sb.AppendLine($"get => GetValue({propName}Property);");
                            sb.AppendLine($"set => SetValue({propName}Property, value);");
                        }
                        sb.AppendLine($"}}");

                        sb.AppendLine();
                    }

                    foreach (var type in group.Key.Hierarchy)
                    {
                        sb.DecrementIndent();
                        sb.AppendLine("}");
                    }

                    var hintName = $"{first.DeclaringNamespace.Replace('.', '_')}_{containingTypes.Replace('.', '_')}_GeneratedProperties.g.cs";
                    spc.AddSource(hintName, sb.ToString());
                }
            });
    }

    private static string? GetNamedArg(AttributeData attr, string name)
    {
        foreach (var (key, value) in attr.NamedArguments)
            if (key == name && !value.IsNull)
                return value.ToCSharpString();
        return null;
    }

    private readonly record struct PropInfo(
        string DeclaringNamespace,
        List<(string Type, bool IsRecord, bool IsStruct, ImmutableArray<string> TypeArguments)> Hierarchy,
        string PropertyName,
        string PropertyType,
        bool IsNullableReference,
        string? DefaultValue,
        string? DefaultValueMember,
        string? OnChangedMethod,
        bool HasBackingField);
}

public class HierarchyComparer : IEqualityComparer<(string DeclaringNamespace, List<(string Type, bool IsRecord, bool IsStruct, ImmutableArray<string> TypeArguments)> Hierarchy)>
{
    public static HierarchyComparer Instance { get; } = new();
    
    public bool Equals(
        (string DeclaringNamespace, List<(string Type, bool IsRecord, bool IsStruct, ImmutableArray<string> TypeArguments)> Hierarchy) x,
        (string DeclaringNamespace, List<(string Type, bool IsRecord, bool IsStruct, ImmutableArray<string> TypeArguments)> Hierarchy) y
    )
    {
        if (x.DeclaringNamespace != y.DeclaringNamespace) return false;

        if (x.Hierarchy.Count != y.Hierarchy.Count) return false;
        for (int i = 0; i < x.Hierarchy.Count; i++)
        {
            if (x.Hierarchy[i].Type != y.Hierarchy[i].Type ||
                x.Hierarchy[i].IsRecord != y.Hierarchy[i].IsRecord ||
                x.Hierarchy[i].IsStruct != y.Hierarchy[i].IsStruct ||
                !x.Hierarchy[i].TypeArguments.SequenceEqual(y.Hierarchy[i].TypeArguments))
            {
                return false;
            }
        }
        return true;
    }

    public int GetHashCode((string DeclaringNamespace, List<(string Type, bool IsRecord, bool IsStruct, ImmutableArray<string> TypeArguments)> Hierarchy) obj)
    {
        // gethashcode without using system.hashcode
        int hash = obj.DeclaringNamespace.GetHashCode();
        foreach (var type in obj.Hierarchy)
        {
            hash = 31 * hash + type.Type.GetHashCode();
            hash = 31 * hash + type.IsRecord.GetHashCode();
            hash = 31 * hash + type.IsStruct.GetHashCode();
            foreach (var arg in type.TypeArguments)
            {
                hash = 31 * hash + arg.GetHashCode();
            }
        }
        return hash;
    }
}
