using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using WorldXaml.Generator.Common;

namespace NFMWorld.Reactor.Generator;

[Generator(LanguageNames.CSharp)]
public class ReactorNodeFactoryGenerator : IIncrementalGenerator
{
    private const string PropertyAttributeFqn = "global::WorldXaml.UI.Base.PropertyAttribute";
    private const string ContentAttributeFqn = "global::WorldXaml.UI.Metadata.ContentAttribute";
    private const string VisualFqn = "global::WorldXaml.UI.Yoga.Visual";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(spc =>
            spc.AddSource("_ReactorPing.g.cs", "// ReactorNodeFactoryGenerator loaded\n"));

        // Find all non-abstract types that extend Visual from ALL assemblies.
        // We need the complete hierarchy to resolve VNode base classes correctly,
        // but we only EMIT factories and VNode classes for types in this project.
        var nodeTypes = context.CompilationProvider
            .SelectMany((compilation, _) =>
            {
                var allTypes = new List<(TypeInfo? Info, IAssemblySymbol Assembly)>();

                void SearchAll(string baseTypeFqn)
                {
                    var baseType = compilation.GetTypeByMetadataName(baseTypeFqn);
                    if (baseType is null) return;

                    foreach (var asm in compilation.SourceModule.ReferencedAssemblySymbols)
                        CollectSubtypes(asm.GlobalNamespace, baseType, asm, allTypes);
                    CollectSubtypes(compilation.Assembly.GlobalNamespace, baseType, compilation.Assembly, allTypes);
                }

                SearchAll("WorldXaml.UI.Yoga.Visual");

                var projectAssembly = compilation.Assembly;
                var seen = new HashSet<string>();
                var deduped = new List<TypeInfo?>();
                foreach (var (info, asm) in allTypes)
                {
                    if (info is { } t && seen.Add(t.FullName))
                    {
                        var isExternal = !SymbolEqualityComparer.Default.Equals(asm, projectAssembly);
                        deduped.Add(t with { IsExternal = isExternal });
                    }
                }

                return System.Collections.Immutable.ImmutableArray.CreateRange(deduped);
            })
            .WithTrackingName("ReactorNodeTypes");

        context.RegisterSourceOutput(
            nodeTypes.Collect(),
            GenerateNodesClass);
    }

    private static void CollectSubtypes(INamespaceSymbol ns, INamedTypeSymbol baseType, IAssemblySymbol asm, List<(TypeInfo? Info, IAssemblySymbol Assembly)> results)
    {
        foreach (var member in ns.GetMembers())
        {
            if (member is INamedTypeSymbol type)
            {
                if (ExtendsType(type, baseType))
                {
                    var info = CollectTypeInfo(type);
                    if (info is not null) results.Add((info, asm));
                }
            }
            if (member is INamespaceSymbol child)
                CollectSubtypes(child, baseType, asm, results);
        }
    }

    private static bool ExtendsType(INamedTypeSymbol symbol, INamedTypeSymbol target)
    {
        var targetFqn = target.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == targetFqn)
                return true;
            current = current.BaseType;
        }
        return false;
    }

    private static TypeInfo? CollectTypeInfo(INamedTypeSymbol symbol)
    {
        var properties = new List<PropInfo>();
        var declaredNames = new HashSet<string>();
        var seen = new HashSet<string>();
        var isFirstType = true;

        // Walk the entire type hierarchy looking for instance properties
        // that have a corresponding static *Property field (convention-based detection),
        // OR are marked with [Property] (backing field generated by PropertyGenerator).
        {
            var current = symbol;
            while (current is not null)
            {
                foreach (var member in current.GetMembers())
                {
                    if (member is not IPropertySymbol prop) continue;
                    if (prop.IsStatic) continue;
                    if (!seen.Add(prop.Name)) continue;

                    // Check for matching static *Property field (e.g. "FlexDirection" → "FlexDirectionProperty")
                    var backingName = prop.Name + "Property";
                    var hasBacking = current.GetMembers(backingName).Any(m => m.IsStatic)
                                     || (current.BaseType?.GetMembers(backingName).Any(m => m.IsStatic) ?? false);

                    // Also accept properties with [Property] attribute — their backing field
                    // is generated by PropertyGenerator (not visible at analysis time).
                    var hasPropAttr = prop.GetAttributes().Any(a =>
                        a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == PropertyAttributeFqn);

                    if (!hasBacking && !hasPropAttr) continue;

                    // Track which type level this property was first declared at
                    if (isFirstType) declaredNames.Add(prop.Name);

                    properties.Add(new PropInfo(
                        Name: prop.Name,
                        TypeFqn: prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        IsValueType: prop.Type.IsValueType,
                        HasDefaultValue: TryGetDefaultValue(prop, out var defaultVal),
                        DefaultValue: defaultVal,
                        IsDeclared: isFirstType
                    ));
                }

                current = current.BaseType;
                isFirstType = false;
            }
        }

        if (properties.Count == 0) return null;

        // Check for [Content] on any property member on type and parents; if found, look for Add(T)
        // on the *property's type* (e.g. NodeChildCollection.Add(Visual))
        string? childType = null;
        bool childIsDeclared = true;
        {
            var current = symbol;
            while (current is not null)
            {
                foreach (var member in current.GetMembers())
                {
                    if (member is not IPropertySymbol contentProp) continue;
                    var hasContent = member.GetAttributes().Any(a =>
                        a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == ContentAttributeFqn);
                    if (!hasContent) continue;

                    // Look for Add(T) on the property's type (e.g. NodeChildCollection)
                    if (contentProp.Type is INamedTypeSymbol propType)
                    {
                        childType = FindAddMethodChildType(propType);
                        goto done;
                    }

                    break;
                }

                current = current.BaseType;
                childIsDeclared = false;
            }
            
            done: ;
        }

        return new TypeInfo(
            FullName: symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            ShortName: symbol.Name,
            Namespace: symbol.ContainingNamespace.ToDisplayString(),
            BaseTypeFqn: symbol.BaseType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            IsAbstract: symbol.IsAbstract,
            Properties: properties,
            DeclaredPropertyNames: declaredNames,
            ChildType: childType,
            ChildIsDeclared: childIsDeclared
        );
    }

    /// <summary>
    /// Finds the T in an Add(T child) method on the type or its base types.
    /// Returns the fully-qualified type name, or null if not found.
    /// </summary>
    private static string? FindAddMethodChildType(INamedTypeSymbol symbol)
    {
        var current = symbol;
        while (current is not null)
        {
            foreach (var method in current.GetMembers().OfType<IMethodSymbol>())
            {
                if (method is { Name: "Add", Parameters.Length: 1, IsStatic: false, ReturnsVoid: true })
                {
                    return method.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                }
            }
            current = current.BaseType;
        }
        return null;
    }

    private static bool TryGetDefaultValue(IPropertySymbol prop, out string? defaultVal)
    {
        defaultVal = null;
        foreach (var attr in prop.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) !=
                PropertyAttributeFqn) continue;

            foreach (var namedArg in attr.NamedArguments)
            {
                if (namedArg is { Key: "DefaultValue", Value.IsNull: false })
                {
                    defaultVal = namedArg.Value.ToCSharpString();
                    return true;
                }
            }
        }
        return false;
    }

    private static string CamelCase(string name)
        => name.Length > 0 ? char.ToLowerInvariant(name[0]) + name[1..] : name;

    private void GenerateNodesClass(SourceProductionContext spc, System.Collections.Immutable.ImmutableArray<TypeInfo?> types)
    {
        var allTypes = new List<TypeInfo>();
        for (int i = 0; i < types.Length; i++)
            if (types[i] is { } t) allTypes.Add(t);

        // Only emit factories + VNode subclasses for types in THIS project.
        // External types are still used for the hierarchy map (base class resolution).
        var localTypes = allTypes.Where(t => !t.IsExternal).ToList();

        // Build full hierarchy map: ALL types (local + external) so local types
        // correctly extend VNode base classes from referenced assemblies.
        var typeToNodeClass = new Dictionary<string, string>();
        foreach (var type in allTypes)
            typeToNodeClass[type.FullName] = type.FullName + "Node";

        // ── Unified Nodes factory class ──────────────────────────────────
        var sbNodes = new IndentedStringBuilder();
        sbNodes.AppendLine("// <auto-generated />");
        sbNodes.AppendLine("#nullable enable");

        if (localTypes.Any(t => !t.IsAbstract))
        {
            foreach (var type in localTypes)
            {
                if (!type.IsAbstract)
                    GenerateFactoryMethod(sbNodes, type);
            }
        }

        // ── Typed VNode subclasses (local only) ──────────────────────────
        var sbTypes = new IndentedStringBuilder();
        sbTypes.AppendLine("// <auto-generated />");
        sbTypes.AppendLine("#nullable enable");

        foreach (var type in localTypes)
        {
            sbTypes.AppendLine();
            sbTypes.AppendLine($"namespace {type.Namespace}");
            sbTypes.AppendLine("{");
            sbTypes.IncrementIndent();
            GenerateNodeClass(sbTypes, type, typeToNodeClass, localTypes);
            sbTypes.DecrementIndent();
            sbTypes.AppendLine("}");
        }

        spc.AddSource("Nodes.g.cs", sbNodes.ToString());
        spc.AddSource("Nodes.Types.g.cs", sbTypes.ToString());
    }

    private static void GenerateNodeClass(IndentedStringBuilder sb, TypeInfo type, Dictionary<string, string> typeToNodeClass, List<TypeInfo> allTypes)
    {
        var nodeName = type.FullName + "Node";

        // Determine the VNode base class: if the native base type has a generated Node class, extend it
        var baseClass = type.BaseTypeFqn is not null && typeToNodeClass.TryGetValue(type.BaseTypeFqn, out var baseNode)
            ? baseNode
            : "global::NFMWorld.Reactor.VisualVNode";

        // Only seal leaf types; use abstract for abstract native types
        var isInherited = allTypes.Any(t2 => t2.BaseTypeFqn == type.FullName);
        var classMod = type.IsAbstract ? "abstract " : isInherited ? "" : "sealed ";

        sb.AppendLine();
        sb.AppendLine($"/// <summary>Typed VNode for <see cref=\"{type.FullName}\"/>.</summary>");
        sb.AppendLine($"public {classMod}class {type.ShortName}Node : {baseClass}");
        sb.AppendLine("{");

        using (sb.Indent())
        {
            if (!type.IsAbstract)
                sb.AppendLine($"public {type.ShortName}Node() {{ }}");
            sb.AppendLine();
            
            sb.AppendLine($"public override Type NodeType => typeof({type.FullName});");
            sb.AppendLine();

            // Generate With* for all hierarchy properties (deduplicated by name)
            foreach (var prop in type.Properties)
            {
                if (!prop.IsDeclared) continue;
                var typeFqn = StripNullable(prop.TypeFqn);
                if (prop.IsValueType)
                    if (typeFqn != prop.TypeFqn)
                        sb.AppendLine($"public {nodeName} With{prop.Name}({prop.TypeFqn} value) => SetPropValNullable<{nodeName}, {typeFqn}>({type.FullName}.{prop.Name}Property, value);");
                    else
                        sb.AppendLine($"public {nodeName} With{prop.Name}({prop.TypeFqn} value) => SetPropVal<{nodeName}, {prop.TypeFqn}>({type.FullName}.{prop.Name}Property, value);");
                else
                    sb.AppendLine($"public {nodeName} With{prop.Name}({prop.TypeFqn} value) => SetProp<{nodeName}, {prop.TypeFqn}>({type.FullName}.{prop.Name}Property, value);");
            }

            // Build set of With* names from properties to avoid shadow conflicts
            var propMethodNames = new HashSet<string>();
            foreach (var prop in type.Properties)
                propMethodNames.Add("With" + prop.Name);

            // Shadow common VNode members with correct return type (skip if a property already provides it)
            if (!propMethodNames.Contains("WithClasses"))
                sb.AppendLine($"public new {nodeName} WithClasses(string? classes) {{ base.WithClasses(classes); return this; }}");
            if (!propMethodNames.Contains("WithKey"))
                sb.AppendLine($"public new {nodeName} WithKey(object? key) {{ base.WithKey(key); return this; }}");

            if (type.ChildType is not null && type.ChildIsDeclared)
            {
                var childNodeType = type.ChildType + "Node";
                if (type.ChildType == VisualFqn)
                {
                    childNodeType = "global::NFMWorld.Reactor.VNode";
                }
                sb.AppendLine();
                sb.AppendLine($"public {nodeName} WithChildren(params ReadOnlySpan<{childNodeType}> children) {{ Children ??= []; Children.AddRange(children); return this; }}");
                sb.AppendLine();
                sb.AppendLine($"public {nodeName} WithChild({childNodeType} child) {{ Children ??= []; Children.Add(child); return this; }}");
            }

            if (!type.IsAbstract)
            {
                sb.AppendLine();
                sb.AppendLine($"public override global::WorldXaml.UI.Yoga.Visual CreateNative() => new {type.FullName}();");
            }
        }

        sb.AppendLine("}");
    }

    private static void GenerateFactoryMethod(IndentedStringBuilder sb, TypeInfo type)
    {
        var factoryNs = type.Namespace;
        sb.AppendLine();
        sb.AppendLine($"namespace {factoryNs}");
        sb.AppendLine("{");
        using (sb.Indent())
        {
            sb.AppendLine("/// <summary>Unified factory methods for all Yoga-backed VNodes in this project.</summary>");
            sb.AppendLine("public static partial class Nodes");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                var returnType = $"{type.FullName}Node";

                sb.AppendLine();
                sb.AppendLine($"/// <summary>Create a <see cref=\"{type.FullName}\"/> VNode.</summary>");
                sb.Append($"public static {returnType} {type.ShortName}(");

                var paramDecls = new List<string>();
                foreach (var prop in type.Properties)
                {
                    var camelName = CamelCase(prop.Name);
                    var paramType = $"NFMWorld.Reactor.Optional<{prop.TypeFqn}>";
                    paramDecls.Add($"{paramType} {camelName} = default");
                }

                if (type.ChildType is not null)
                {
                    var childNodeType = type.ChildType + "Node";
                    if (type.ChildType == VisualFqn)
                        childNodeType = "NFMWorld.Reactor.VNode";
                    else if (!childNodeType.StartsWith("global::"))
                        childNodeType = $"global::{childNodeType}";
                    paramDecls.Add($"params ReadOnlySpan<{childNodeType}> children");
                }

                using (sb.Indent())
                {
                    var first = true;
                    foreach (var param in paramDecls)
                    {
                        if (first) { first = false; }
                        else { sb.AppendLine(","); }
                        sb.Append(param);
                    }
                }

                sb.AppendLine(")");
                sb.AppendLine("{");

                using (sb.Indent())
                using (sb.Indent())
                {
                    sb.AppendLine($"var n = new {returnType}();");
                    sb.AppendLine();

                    foreach (var prop in type.Properties)
                    {
                        var camelName = CamelCase(prop.Name);
                        sb.AppendLine($"if ({camelName}.HasValue) n.With{prop.Name}({camelName}.Value);");
                    }

                    if (type.ChildType is not null)
                        sb.AppendLine("if (children.Length > 0) n.WithChildren(children);");

                    sb.AppendLine();
                    sb.AppendLine("return n;");
                }

                sb.AppendLine("}");
            }
            sb.AppendLine("}");
        }
        sb.AppendLine("}");
    }

    /// <summary>Strips Nullable&lt;T&gt; wrappers, returning T. E.g. "System.Nullable&lt;float&gt;" → "float".</summary>
    private static string StripNullable(string fqn)
    {
        if (fqn.StartsWith("System.Nullable<") && fqn.EndsWith(">"))
            return fqn.Substring(18, fqn.Length - 19); // Strip "System.Nullable<" and ">"
        if (fqn.EndsWith("?"))
            return fqn[..^1];
        return fqn;
    }

    /// <summary>Simplifies a globally-qualified type name relative to a namespace.</summary>
    private static string SimplifyType(string fqn, string ns)
    {
        fqn = StripNullable(fqn);
        var nsPrefix = $"global::{ns}.";
        if (fqn.StartsWith(nsPrefix))
            return fqn.Substring(nsPrefix.Length);
        return fqn;
    }

    private readonly record struct TypeInfo(
        string FullName,
        string ShortName,
        string Namespace,
        string? BaseTypeFqn,
        bool IsAbstract,
        List<PropInfo> Properties,
        HashSet<string> DeclaredPropertyNames,
        string? ChildType,
        bool ChildIsDeclared,
        bool IsExternal = false);

    private readonly record struct PropInfo(
        string Name,
        string TypeFqn,
        bool IsValueType,
        bool HasDefaultValue,
        string? DefaultValue,
        bool IsDeclared);
}
