<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NFMWorld.Library\NFMWorld.Library.csproj" />
      <ProjectReference Include="..\WorldXaml\WorldXaml.Generator\WorldXaml.Generator.csproj" PrivateAssets="all" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
      <ProjectReference Include="..\WorldXaml\WorldXaml.UI.Base\WorldXaml.UI.Base.csproj" />
      <ProjectReference Include="..\WorldXaml\WorldXaml.UI.Yoga\WorldXaml.UI.Yoga.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaXaml Include="Hud\CentralTextView.xaml" />
      <AvaloniaXaml Include="Hud\LapTimerSplitsView.xaml" />
      <AvaloniaXaml Include="Hud\PowerDamageBars.xaml" />
      <AvaloniaXaml Include="Hud\TTLapTimerSplitsView.xaml" />
    </ItemGroup>

</Project>
