using nfm_world.ui.yoga.xaml;

// Assembly-level XAML namespace mappings
[assembly: XmlnsDefinition("clr-namespace:nfm_world.ui.yoga", "nfm_world.ui.yoga")]
[assembly: XmlnsDefinition("clr-namespace:nfm_world.ui.elements", "nfm_world.ui.elements")]
[assembly: XmlnsDefinition("clr-namespace:nfm_world.ui.yoga.xaml", "nfm_world.ui.yoga.xaml")]
[assembly: XmlnsDefinition("clr-namespace:System;assembly=mscorlib", "System")]

namespace nfm_world.ui.yoga.xaml;

/// <summary>
/// Entry point for loading and populating XAML-defined views at runtime.
/// This class provides methods to work with compiled XAML types.
/// </summary>
public static class XamlLoader
{
    /// <summary>
    /// Creates a service provider with default services for XAML instantiation.
    /// </summary>
    public static IServiceProvider CreateDefaultServiceProvider(object? rootObject = null, string? baseUri = null)
    {
        var provider = new XamlServiceProvider();

        var rootObjectProvider = new RootObjectProviderImpl
        {
            RootObject = rootObject,
            IntermediateRootObject = rootObject
        };
        provider.AddService<IRootObjectProvider>(rootObjectProvider);

        var uriContext = new UriContextImpl
        {
            BaseUri = baseUri != null ? new Uri(baseUri) : null
        };
        provider.AddService<IUriContext>(uriContext);

        var provideValueTarget = new ProvideValueTargetImpl();
        provider.AddService<IProvideValueTarget>(provideValueTarget);

        return provider;
    }

    /// <summary>
    /// Populates a XAML-based view by calling its generated Populate method.
    /// </summary>
    /// <typeparam name="T">The type of the view (must have a static Populate method generated by XamlX).</typeparam>
    /// <param name="instance">The instance to populate.</param>
    /// <param name="serviceProvider">Optional service provider. If null, a default one is created.</param>
    public static void Populate<T>(T instance, IServiceProvider? serviceProvider = null) where T : class
    {
        serviceProvider ??= CreateDefaultServiceProvider(instance);

        var type = typeof(T);
        var populateMethod = type.GetMethod("Populate",
            System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);

        if (populateMethod == null)
        {
            throw new InvalidOperationException(
                $"Type {type.FullName} does not have a generated Populate method. " +
                "Ensure the XAML file is properly compiled with the XamlX build task.");
        }

        populateMethod.Invoke(null, [serviceProvider, instance]);
    }

    /// <summary>
    /// Creates and populates a XAML-based view.
    /// </summary>
    /// <typeparam name="T">The type of the view (must have a static Build method generated by XamlX).</typeparam>
    /// <param name="serviceProvider">Optional service provider. If null, a default one is created.</param>
    /// <returns>A new instance of the view with XAML properties applied.</returns>
    public static T Create<T>(IServiceProvider? serviceProvider = null) where T : class
    {
        var type = typeof(T);
        var buildMethod = type.GetMethod("Build",
            System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);

        if (buildMethod == null)
        {
            throw new InvalidOperationException(
                $"Type {type.FullName} does not have a generated Build method. " +
                "Ensure the XAML file is properly compiled with the XamlX build task.");
        }

        serviceProvider ??= CreateDefaultServiceProvider();

        return (T)buildMethod.Invoke(null, [serviceProvider])!;
    }
}
