<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FNA.Math\FNA.Math.csproj" />
      <ProjectReference Include="..\MemoryPack\src\MemoryPack\MemoryPack.csproj" />
      <ProjectReference Include="..\MemoryPack\src\MemoryPack.Generator\MemoryPack.Generator.csproj" PrivateAssets="all" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>
    
    <ItemGroup>
        <CompilerVisibleProperty Include="MemoryPackGenerator_TypeScriptOutputDirectory" />
        <CompilerVisibleProperty Include="MemoryPackGenerator_TypeScriptImportExtension" />
        <CompilerVisibleProperty Include="MemoryPackGenerator_TypeScriptConvertPropertyName" />
        <CompilerVisibleProperty Include="MemoryPackGenerator_TypeScriptEnableNullableTypes" />
    </ItemGroup>
    <PropertyGroup>
        <MemoryPackGenerator_TypeScriptOutputDirectory>$(MSBuildProjectDirectory)\..\nfm-world\data\html\src\shared\memorypack</MemoryPackGenerator_TypeScriptOutputDirectory>
        <MemoryPackGenerator_TypeScriptEnableNullableTypes>true</MemoryPackGenerator_TypeScriptEnableNullableTypes>
    </PropertyGroup>

</Project>
